/*
数据库建表 SQL（在 Supabase SQL Editor 中执行）：

create table user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  learning_queue jsonb default '[]'::jsonb,
  ignore_word_pool jsonb default '[]'::jsonb,
  updated_at timestamp with time zone default now()
);

-- 允许用户读写自己的数据行
alter table user_progress enable row level security;

create policy "用户可以读取自己的进度"
  on user_progress for select
  using (auth.uid() = user_id);

create policy "用户可以插入自己的进度"
  on user_progress for insert
  with check (auth.uid() = user_id);

create policy "用户可以更新自己的进度"
  on user_progress for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
*/

import { getSupabase, isSupabaseConfigured } from '../utils/supabase'

export async function fetchUserProgress(userId) {
  if (!isSupabaseConfigured()) return {}
  const sb = getSupabase()
  if (!sb) return {}
  const { data, error } = await sb
    .from('user_progress')
    .select('learning_queue, ignore_word_pool')
    .eq('user_id', userId)
    .maybeSingle()
  if (error) throw error
  return data || {}
}

export async function upsertUserProgress(userId, updates) {
  if (!isSupabaseConfigured()) return
  const sb = getSupabase()
  if (!sb) return
  const payload = {
    user_id: userId,
    updated_at: new Date().toISOString(),
    ...updates,
  }
  const { error } = await sb.from('user_progress').upsert(payload, {
    onConflict: 'user_id',
  })
  if (error) throw error
}
